# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrest',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('OCA', models.CharField(max_length=20, null=True, blank=True)),
                ('Agency_Name', models.CharField(max_length=150, null=True, blank=True)),
                ('ORI', models.CharField(max_length=50, null=True, blank=True)),
                ('Date_Arrested', models.DateField(null=True, blank=True)),
                ('Time_Arrested', models.TimeField(null=True, blank=True)),
                ('Prints_Taken', models.NullBooleanField()),
                ('Photos_Taken', models.NullBooleanField()),
                ('Fingerprint_Card_Number_CKN', models.CharField(max_length=30, null=True, blank=True)),
                ('Arrest_Tract', models.CharField(max_length=20, null=True, blank=True)),
                ('Residence_Tract', models.CharField(max_length=20, null=True, blank=True)),
                ('Arrest_Number', models.CharField(max_length=20, null=True, blank=True)),
                ('Name', models.CharField(max_length=250, null=True, blank=True)),
                ('DOB', models.DateField(null=True, blank=True)),
                ('Age', models.CharField(max_length=5, null=True, blank=True)),
                ('Race', models.CharField(max_length=5, null=True, blank=True)),
                ('Sex', models.CharField(default=b'', max_length=2, null=True, blank=True, choices=[(b'M', b'Male'), (b'F', b'Female'), (b'', b'Unspecified')])),
                ('Place_of_Birth', models.CharField(max_length=50, null=True, blank=True)),
                ('Country_of_Citizenship', models.CharField(max_length=50, null=True, blank=True)),
                ('Address', models.CharField(max_length=250, null=True, blank=True)),
                ('Arrestee_Phone', models.CharField(max_length=20, null=True, blank=True)),
                ('Occupation', models.CharField(max_length=80, null=True, blank=True)),
                ('Residency_Status', models.CharField(max_length=15, null=True, blank=True)),
                ('Employer_Name', models.CharField(max_length=80, null=True, blank=True)),
                ('Employer_Address', models.CharField(max_length=150, null=True, blank=True)),
                ('Employer_Phone', models.CharField(max_length=100, null=True, blank=True)),
                ('Also_Known_As', models.CharField(max_length=20, null=True, blank=True)),
                ('Hgt', models.CharField(max_length=10, null=True, blank=True)),
                ('Wgt', models.IntegerField(null=True, blank=True)),
                ('Hair', models.CharField(max_length=10, null=True, blank=True)),
                ('Eyes', models.CharField(max_length=10, null=True, blank=True)),
                ('Skin_Tone', models.CharField(max_length=10, null=True, blank=True)),
                ('Consumed_Drug_Alcohol', models.CharField(max_length=10, null=True, blank=True)),
                ('Scars_Marks_Tattoos', models.CharField(max_length=150, null=True, blank=True)),
                ('Social_Security', models.CharField(max_length=20, null=True, blank=True)),
                ('OLN_and_State', models.CharField(max_length=50, null=True, blank=True)),
                ('Misc_Number_and_Type', models.CharField(max_length=50, null=True, blank=True)),
                ('Nearest_Relative_Name', models.CharField(max_length=100, null=True, blank=True)),
                ('Nearest_Relative_Address', models.CharField(max_length=150, null=True, blank=True)),
                ('Nearest_Relative_Phone', models.CharField(max_length=20, null=True, blank=True)),
                ('If_Armed_Type_of_Weapon', models.CharField(max_length=50, null=True, blank=True)),
                ('Arrest_Type', models.CharField(max_length=20, null=True, blank=True)),
                ('Place_of_Arrest', models.CharField(max_length=100, null=True, blank=True)),
                ('Charge1', models.CharField(max_length=100, null=True, blank=True)),
                ('Charge1_Type', models.CharField(max_length=15, null=True, blank=True)),
                ('Charge1_Counts', models.IntegerField(null=True, blank=True)),
                ('Charge1_DCI_Code', models.IntegerField(null=True, blank=True)),
                ('Charge1_Offense_Jurisdiction', models.CharField(max_length=50, null=True, blank=True)),
                ('Charge1_Statute_Number', models.CharField(max_length=20, null=True, blank=True)),
                ('Charge1_Warrant_Date', models.CharField(max_length=15, null=True, blank=True)),
                ('Charge2', models.CharField(max_length=100, null=True, blank=True)),
                ('Charge2_Type', models.CharField(max_length=15, null=True, blank=True)),
                ('Charge2_Counts', models.IntegerField(null=True, blank=True)),
                ('Charge2_DCI_Code', models.IntegerField(null=True, blank=True)),
                ('Charge2_Offense_Jurisdiction', models.CharField(max_length=50, null=True, blank=True)),
                ('Charge2_Statute_Number', models.CharField(max_length=20, null=True, blank=True)),
                ('Charge2_Warrant_Date', models.CharField(max_length=15, null=True, blank=True)),
                ('Charge3', models.CharField(max_length=100, null=True, blank=True)),
                ('Charge3_Type', models.CharField(max_length=15, null=True, blank=True)),
                ('Charge3_Counts', models.IntegerField(null=True, blank=True)),
                ('Charge3_DCI_Code', models.IntegerField(null=True, blank=True)),
                ('Charge3_Offense_Jurisdiction', models.CharField(max_length=50, null=True, blank=True)),
                ('Charge3_Statute_Number', models.CharField(max_length=20, null=True, blank=True)),
                ('Charge3_Warrant_Date', models.CharField(max_length=15, null=True, blank=True)),
                ('VYR', models.IntegerField(null=True, blank=True)),
                ('Make', models.CharField(max_length=10, null=True, blank=True)),
                ('Model', models.CharField(max_length=10, null=True, blank=True)),
                ('Style', models.CharField(max_length=10, null=True, blank=True)),
                ('Color', models.CharField(max_length=10, null=True, blank=True)),
                ('Plate_No_and_State', models.CharField(max_length=50, null=True, blank=True)),
                ('VIN', models.CharField(max_length=100, null=True, blank=True)),
                ('Vehicle_Status', models.CharField(max_length=50, null=True, blank=True)),
                ('Vehicle_Status_Datetime', models.DateTimeField(null=True, blank=True)),
                ('Datetime_Confined', models.DateTimeField(null=True, blank=True)),
                ('Place_Confined', models.CharField(max_length=100, null=True, blank=True)),
                ('Committing_Magistrate', models.CharField(max_length=100, null=True, blank=True)),
                ('Type_Bond', models.CharField(max_length=20, null=True, blank=True)),
                ('Bond_Amount', models.CharField(max_length=20, null=True, blank=True)),
                ('Trial_Date', models.DateField(null=True, blank=True)),
                ('Court_of_Trial', models.CharField(max_length=50, null=True, blank=True)),
                ('City_of_Court', models.CharField(max_length=50, null=True, blank=True)),
                ('Assisting_Officer', models.CharField(max_length=100, null=True, blank=True)),
                ('Released_By', models.CharField(max_length=100, null=True, blank=True)),
                ('Datetime_Released', models.DateTimeField(null=True, blank=True)),
                ('Drug1_Suspected_Type', models.CharField(max_length=100, null=True, blank=True)),
                ('Drug1_DCI', models.IntegerField(null=True, blank=True)),
                ('Drug1_Status', models.CharField(max_length=25, null=True, blank=True)),
                ('Drug1_Quantity', models.CharField(max_length=10, null=True, blank=True)),
                ('Drug1_Activities', models.CharField(max_length=150, null=True, blank=True)),
                ('Drug2_Suspected_Type', models.CharField(max_length=100, null=True, blank=True)),
                ('Drug2_DCI', models.IntegerField(null=True, blank=True)),
                ('Drug2_Status', models.CharField(max_length=25, null=True, blank=True)),
                ('Drug2_Quantity', models.CharField(max_length=10, null=True, blank=True)),
                ('Drug2_Activities', models.CharField(max_length=150, null=True, blank=True)),
                ('Comp', models.CharField(max_length=15, null=True, blank=True)),
                ('Comp_Name', models.CharField(max_length=100, null=True, blank=True)),
                ('Comp_Address', models.CharField(max_length=100, null=True, blank=True)),
                ('Comp_Phone', models.CharField(max_length=20, null=True, blank=True)),
                ('Narrative', models.TextField(null=True, blank=True)),
                ('Arresting_Officer_Signature', models.CharField(max_length=150, null=True, blank=True)),
                ('Date_Submitted', models.DateField(null=True, blank=True)),
                ('Time_Submitted', models.TimeField(null=True, blank=True)),
                ('Supervisor_Signature', models.CharField(max_length=100, null=True, blank=True)),
                ('Case_Status', models.CharField(max_length=25, null=True, blank=True)),
                ('Case_Disposition', models.CharField(max_length=50, null=True, blank=True)),
                ('Arrestee_Signature', models.CharField(max_length=150, null=True, blank=True)),
                ('pdf', models.CharField(max_length=250, null=True, blank=True)),
                ('city', models.CharField(max_length=50, null=True, blank=True)),
                ('state', models.CharField(max_length=3, null=True, blank=True)),
            ],
        ),
    ]
